---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs

# Open Routing for Oper Api
Director:
  rules:
    'authapi/v1'        : 'AuthenticationAPI'
    'profileapi/v1'     : 'MyProfileAPI'
    'personalapi/v1'    : 'MyPersonalDetailsAPI'

# RestfulAPI config
AuthenticationAPI:
  allowed_actions:
    - postRegistration
    - postCheckLogin
    - postForgotPassword
    - postUpdatePassword
    - postLogout

MyProfileAPI:
  allowed_actions:
    - MyProfile
    - UpdateProfile
    - MyPersonalDetails
    - UpdatePersonalDetails
    - UploadMyPictures
    - UpdateMyPictures
    - DeleteMyPictures

MyPersonalDetailsAPI:
  allowed_actions:
    - postManagerDetails
    - postUpdateManagerDetails
    - postAttorneyDetails
    - postUpdateAttorneyDetails
    - postTrainerDetails
    - postUpdateTrainerDetails
    - postAthleteDetails
    - postUpdateAthleteDetails
    - postGeneralDetails
    - postUpdateGeneralDetails

Member:
  extensions:
    - RESTMember

# replace files instead of versioning
Upload:
  replaceFile: false

# show an overwrite warning
UploadField:
  defaultConfig:
    overwriteWarning: false

SSViewer:
  theme: 'simple'